#
# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause
#
libcpio = ${SEL4_LIBS_PATH}/libcpio

cpio-strip: cpio-strip.c ${libcpio}/src/cpio.c ${libcpio}/include/cpio/cpio.h
	@echo " [CC] $@"
	${Q}${CC} -W -Wall -Wextra -std=c99 -I${libcpio}/include cpio-strip.c ${libcpio}/src/cpio.c -o $@

clean:
	rm cpio-strip
