#!/usr/bin/env python

#
# Copyright 2016, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

'''
Reads in two JSON strings on stdin, separated by a NULL byte and then diffs the
two. Returns 0 if they are equivalent.
'''

import datadiff, json, sys

try:
    data = sys.stdin.read()
    a, b = data.split('\x00')
    diff = datadiff.diff(json.loads(a), json.loads(b))
    if str(diff) == '':
        sys.exit(0)
except Exception:
    pass
sys.exit(1)
